site_name: Arca Documentation
site_url: https://bceln.github.io/arca-docs
repo_url: https://github.com/bceln/arca-docs
edit_uri: edit/main/docs


theme:
  name: material
  logo: 'assets/Arca_Logo_web.svg'
  palette:
    primary: 'cyan'
    accent: 'purple'
  language: 'en'
  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
  icon:
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - admonition
  - footnotes
  - toc:
        permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About:
    - About Arca: about/about-arca.md
    - Support: about/support.md
  - How-To in Islandora 2:
    - Theming Customizations: how-to/theming/customizations.md
    - Display Customizations:
      - Custom URLs for repository items: how-to/display/pathauto.md
      - Displaying usage data: how-to/display/usage.md
    - Managing Objects:
      - Ingest Guide: how-to/managing-content/ingest-guide.md
      - Managing Media: how-to/managing-content/media.md
      - Remote and Embedded Media: how-to/managing-content/remote-embed.md
      - 3D Objects: how-to/managing-content/3d-objects.md
    - Processes:
      - Self-submission: how-to/processes/self-submission.md
  - Troubleshooting:
    - Troubleshooting: troubleshooting/troubleshooting.md
    - Islandora 7 troubleshooting: troubleshooting/troubleshooting-i7.md
  - Migration:
    - Timeline: migration/migration-timeline.md
    - Metadata Mapping: migration/metadata-mapping.md
    - Migration Tasks:
      - Prepare Your Site: migration/migration-tasks/migration-preparation.md
      - Metadata Corrections: migration/migration-tasks/metadata-corrections.md
      - Bulk Metadata Updates: migration/migration-tasks/bulk-metadata-updates.md
