site_name: Arca Documentation
site_url: https://bceln.github.io/arca-docs
repo_url: https://github.com/bceln/arca-docs
edit_uri: edit/main/docs


theme:
  name: material
  logo: 'assets/Arca_Logo_web.svg'
  palette:
    primary: 'cyan'
    accent: 'purple'
  language: 'en'
  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
  icon:
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - admonition
  - footnotes
  - toc:
        permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About:
    - About Arca: about/about-arca.md
    - Support: about/support.md
    - Contribute to Arca Docs: about/contributing.md
  - Training: training/training.md
  - How-To in Islandora 2:
    - Theming Customizations: how-to/theming/customizations.md
    - Display Customizations:
      - Custom URLs for repository items: how-to/display/pathauto.md
      - Download link permissions: how-to/display/download-links.md
      - Displaying usage data: how-to/display/usage.md
      - Collection Display: how-to/display/collection-display.md
      - Metadata Display: how-to/display/metadata-display-customizations.md
      - Comments: how-to/display/comments.md
      - Links to Socials: how-to/display/social-links.md
    - Metadata:
      - Taxonomies: how-to/metadata/taxonomies.md
    - Managing Objects:
      - Ingest Guide: how-to/managing-content/ingest-guide.md
      - Managing Media: how-to/managing-content/media.md
      - Remote and Embedded Media: how-to/managing-content/remote-embed.md
      - 3D Objects: how-to/managing-content/3d-objects.md
    - Search:
      - Advanced search: how-to/search/advanced-search.md
    - Access Controls:
      - Embargoes: how-to/access-control/embargo.md
    - Processes:
      - Self-submission: how-to/processes/self-submission.md
    - Usage Statistics:
      - Collecting statistics: how-to/statistics/statistics.md
  - Troubleshooting:
    - Troubleshooting: troubleshooting/troubleshooting.md
    - FAQs: troubleshooting/faqs.md
    - Islandora 7 troubleshooting: troubleshooting/troubleshooting-i7.md
  - Migration:
    - Timeline: migration/migration-timeline.md
    - Schedule: migration/migration-schedule.md
    - Metadata Mapping: migration/metadata-mapping.md
    - Migration Tasks:
      - Prepare Your Site: migration/migration-tasks/migration-preparation.md
      - Metadata Corrections: migration/migration-tasks/metadata-corrections.md
      - Bulk Metadata Updates: migration/migration-tasks/bulk-metadata-updates.md
      - Pre-Migration Tasks: migration/migration-tasks/pre-migration.md
      - Post-Migration tasks: migration/migration-tasks/post-migration.md
