site_name: Arca Documentation
site_url: https://bceln.github.io
nav:
  - Home: index.md
  - About:
    - About Arca: about/about-arca.md
    - Support: about/support.md
  - Migration:
    - Timeline: migration/migration-timeline.md
